// Package nodepassword reproduces rke2's node-password handling.
//
// rke2 gives each node a random secret, kept at /etc/rancher/node/password on
// the node and stored server-side - hashed - as a Secret named
// "<node>.node-password.rke2" in kube-system. It is what stops one node from
// requesting certificates in another node's name.
//
// The hash format and scrypt parameters below are byte-compatible with
// k3s/rke2 (pkg/authenticator/hash), so the Secrets this shim writes are
// readable by a real rke2 server and vice versa. TestVerifyRealRKE2Hash pins
// that against a hash generated by an actual rke2 server.
package nodepassword

import (
	"crypto/rand"
	"crypto/subtle"
	"encoding/base64"
	"errors"
	"fmt"

	"golang.org/x/crypto/scrypt"
)

const (
	version    = 1
	hashFormat = "$%d:%x:%d:%d:%d:%s"

	// Identical to k3s hash.NewSCrypt(). N is a log2 exponent, not the value.
	paramN       = 15
	paramR       = 8
	paramP       = 1
	paramKeyLen  = 64
	paramSaltLen = 8
)

var ErrMismatch = errors.New("node password mismatch")

// CreateHash hashes a node password for storage.
func CreateHash(secret string) (string, error) {
	salt := make([]byte, paramSaltLen)
	if _, err := rand.Read(salt); err != nil {
		return "", err
	}
	dk, err := scrypt.Key([]byte(secret), salt, 1<<paramN, paramR, paramP, paramKeyLen)
	if err != nil {
		return "", err
	}
	enc := base64.RawStdEncoding.EncodeToString(dk)
	return fmt.Sprintf(hashFormat, version, salt, paramN, paramR, paramP, enc), nil
}

// VerifyHash reports whether secret matches a stored hash, in constant time.
func VerifyHash(hash, secret string) error {
	var (
		ver, n uint
		r, p   int
		enc    string
		salt   []byte
	)
	if _, err := fmt.Sscanf(hash, hashFormat, &ver, &salt, &n, &r, &p, &enc); err != nil {
		return fmt.Errorf("malformed node password hash: %w", err)
	}
	if ver != version {
		return fmt.Errorf("hash version %d is not supported (want %d)", ver, version)
	}
	dk, err := base64.RawStdEncoding.DecodeString(enc)
	if err != nil {
		return fmt.Errorf("malformed node password hash: %w", err)
	}
	// Honour the parameters recorded in the hash rather than our defaults, so
	// hashes written by other rke2 versions still verify.
	want, err := scrypt.Key([]byte(secret), salt, 1<<n, r, p, len(dk))
	if err != nil {
		return err
	}
	if subtle.ConstantTimeCompare(dk, want) != 1 {
		return ErrMismatch
	}
	return nil
}
