package nodepassword

import (
	"fmt"
	"testing"
)

// LAB FIXTURE - not a live credential.
//
// Generated by a real rke2 v1.31.8+rke2r1 server on a disposable lab VM: the
// plaintext from /etc/rancher/node/password and the hash it wrote to
// kube-system/<node>.node-password.rke2. That cluster is gone; this pair grants
// access to nothing. It is committed on purpose, because a hash produced by
// upstream rke2 is the only thing that can prove our hashing stays
// byte-compatible with theirs. Secret scanners will flag it - that is expected.
//
// This pins byte-compatibility with upstream. If rke2 ever changes its hashing,
// this test fails and the Secrets we write stop being interchangeable with a
// real server's - which is exactly the kind of drift we want to hear about.
const (
	realRKE2Password = "ea5b0cd0c94c08b2b5a6ae7d53292db2"
	realRKE2Hash     = "$1:372a19103e507ba9:15:8:1:brQyrCKpzdVf3O5fIHs2rHTe3ebVSLR+cU0RXP42Paoj/7DMTer3JqGUHVdJfpf0r6Mi+e3unSqg0aG+16/z5A"
)

func TestVerifyRealRKE2Hash(t *testing.T) {
	if err := VerifyHash(realRKE2Hash, realRKE2Password); err != nil {
		t.Fatalf("failed to verify a hash produced by a real rke2 server: %v", err)
	}
	if err := VerifyHash(realRKE2Hash, "wrong-password"); err == nil {
		t.Fatal("a wrong password verified against the real rke2 hash")
	}
}

func TestRoundTrip(t *testing.T) {
	h, err := CreateHash("s3cret")
	if err != nil {
		t.Fatal(err)
	}
	if err := VerifyHash(h, "s3cret"); err != nil {
		t.Fatalf("round trip failed: %v", err)
	}
	if err := VerifyHash(h, "s3cre7"); err == nil {
		t.Fatal("wrong password accepted")
	}
}

// Our output must be parseable by the same scanner rke2 uses.
func TestOutputFormatMatchesUpstream(t *testing.T) {
	h, err := CreateHash("x")
	if err != nil {
		t.Fatal(err)
	}
	var (
		ver, n uint
		r, p   int
		enc    string
		salt   []byte
	)
	if _, err := fmt.Sscanf(h, hashFormat, &ver, &salt, &n, &r, &p, &enc); err != nil {
		t.Fatalf("upstream scanner could not parse our hash %q: %v", h, err)
	}
	if ver != 1 || n != 15 || r != 8 || p != 1 || len(salt) != 8 {
		t.Errorf("params drifted: ver=%d n=%d r=%d p=%d saltlen=%d", ver, n, r, p, len(salt))
	}
}

func TestRejectsMalformed(t *testing.T) {
	for _, h := range []string{"", "not-a-hash", "$2:aabb:15:8:1:zzz", "$1:xx"} {
		if err := VerifyHash(h, "x"); err == nil {
			t.Errorf("malformed hash %q was accepted", h)
		}
	}
}
